# Generated by Django 5.2.1 on 2025-06-13 02:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='route',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='route',
            name='current_path',
            field=models.CharField(max_length=100, verbose_name='Текущий путь'),
        ),
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.TextField(verbose_name='Описание маршрута'),
        ),
        migrations.AlterField(
            model_name='route',
            name='planned_path',
            field=models.CharField(max_length=100, verbose_name='Запланированный путь'),
        ),
        migrations.AlterField(
            model_name='route',
            name='status',
            field=models.CharField(choices=[('normal', 'Нормальный'), ('warning', 'Предупреждение'), ('alert', 'Тревога'), ('emergency', 'Чрезвычайная ситуация')], default='normal', max_length=20, verbose_name='Статус'),
        ),
    ]
