# Generated by Django 5.2.1 on 2025-06-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_route_created_at_route_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='type',
            field=models.CharField(choices=[('driver', 'Водитель'), ('dispatcher', 'Диспетчер')], max_length=30, unique=True),
        ),
    ]
